/**
 * Deserializer module is used by the code generated by {@link churi/compiler! compiler}.
 *
 * __Deserializer API considered unstable__ and may change for minor releases.

* @module churi/deserializer
 */
export * from './async-ucd-reader.js';
export * from './sync-ucd-reader.js';
export * from './ucd-reader.js';
export * from './ucrx-non-finite.js';
