/**
 * Deserializer module is used by the code generated by {@link @hatsy/churi/compiler! compiler}.
 *
 * __Deserializer API considered unstable__ and may change for minor releases.

* @module @hatsy/churi/deserializer
 */
export * from './async-ucd-reader.js';
export * from './read-uc-list.js';
export * from './sync-ucd-reader.js';
export * from './ucd-entity-handler.js';
export * from './ucd-entity-reader.js';
export * from './ucd-read-non-finite.js';
export * from './ucd-reader.js';
