import { UcToken } from '../syntax/uc-token.js';

/**
 * Charge receiver interface.
 *
 * Typically, the implementations of this interface generated by compiler.
 */
export interface Ucrx {
  /**
   * Array of expected value types.
   *
   * Used for error messages.
   */
  get types(): readonly string[];

  bol(value: boolean): 0 | 1;
  big(value: bigint): 0 | 1;
  ent(value: readonly UcToken[]): 0 | 1;
  nls(): Ucrx | undefined;
  num(value: number): 0 | 1;
  str(value: string): 0 | 1;

  /**
   * Starts map entry charge.
   *
   * @param key - Target entry key.
   *
   * @returns Either entry receiver, `0` if a map is not permitted, or `undefined` if target map does not contain entry
   * with the given `key`.
   */
  for(key: PropertyKey): Ucrx | 0 | undefined;

  /**
   * Finishes map charge.
   *
   * Called after {@link for} call(s) only.
   */
  map(): void;

  /**
   * Starts or continues a list charge.
   *
   * May be called before or after the first item charged.
   *
   * May be called multiple times per list.
   *
   * @returns `1` if a list permitted, or `0` otherwise.
   */
  em(): 0 | 1;

  /**
   * Finishes list charge.
   *
   * Called after {@link em} call(s) only.
   */
  ls(): void;

  nul(): 0 | 1;
}
