import { DESERIALIZER_MODULE, SERIALIZER_MODULE } from '../../impl/module-names.js';
import { UcProcessing } from '../uc-processing.js';
import { ucSchemaName } from '../uc-schema-name.js';
import { UcSchema, UcSchema__symbol } from '../uc-schema.js';

/**
 * URI charge list represented as JavaScript array.
 *
 * @typeParam TItem - List item value type.
 */
export type UcList<TItem = unknown> = TItem[];

export namespace UcList {
  /**
   * URI charge schema definition for JavaScript {@link UcList array} serialized as list.
   *
   * Such schema can be built with {@link ucList} function.
   *
   * @typeParam TItemSpec - Type of list item schema specifier.
   */
  export interface Schema<
    TItem = unknown,
    TItemSpec extends UcSchema.Spec<TItem> = UcSchema.Spec<TItem>,
  > extends UcSchema<TItem[]> {
    readonly type: 'list';

    /**
     * List item schema.
     */
    readonly item: UcSchema.Of<TItemSpec>;
  }

  export namespace Schema {
    /**
     * Schema specifier of URI charge list.
     *
     * @typeParam TItemSpec - Type of list item schema specifier.
     */
    export type Spec<TItem, TItemSpec extends UcSchema.Spec<TItem> = UcSchema.Spec<TItem>> =
      | Schema<TItem, TItemSpec>
      | Ref<TItem, TItemSpec>;

    /**
     * Reference to schema of URI charge list.
     *
     * @typeParam TItemSpec - Type of list item schema specifier.
     */
    export type Ref<
      TItem,
      TItemSpec extends UcSchema.Spec<TItem> = UcSchema.Spec<TItem>,
    > = UcSchema.Ref<TItem[], Schema<TItem, TItemSpec>>;

    /**
     * Additional options for URI charge list schema.
     */
    export interface Options {
      /**
       * Unique schema identifier.
       *
       * @defaultValue Autogenerated string.
       */
      readonly id?: string | UcSchema.Class | undefined;
    }
  }
}

/**
 * Creates a reference to URI charge schema for JavaScript {@link UcList array} serialized as list.
 *
 * @typeParam TItemSpec - Type of list item schema specifier.
 * @param itemSpec - List item schema specifier.
 *
 * @returns Reference to schema of URI charge list.
 */
export function ucList<TItem, TItemSpec extends UcSchema.Spec<TItem> = UcSchema.Spec<TItem>>(
  itemSpec: TItemSpec,
  options?: UcList.Schema.Options,
): UcList.Schema.Ref<TItem, TItemSpec>;

export function ucList<TItem, TItemSpec extends UcSchema.Spec<TItem> = UcSchema.Spec<TItem>>(
  itemSpec: TItemSpec,
  { id }: UcList.Schema.Options = {},
): UcList.Schema.Ref<TItem, TItemSpec> {
  return {
    [UcSchema__symbol]: resolver => {
      const item = resolver.schemaOf(itemSpec) as UcSchema.Of<TItemSpec>;

      return {
        type: 'list',
        id: id ?? `list_${++UcList$idSeq}`,
        process: UcList$processing,
        item,
        toString() {
          return `${ucSchemaName(item)}[]`;
        },
      };
    },
  };
}

let UcList$idSeq = 0;

const UcList$processing: UcProcessing = {
  deserializer: {
    from: DESERIALIZER_MODULE,
    symbol: 'ListUcrxTemplate',
    method: 'configure',
  },
  serializer: {
    from: SERIALIZER_MODULE,
    symbol: 'ucsConfigureList',
  },
};
