/**
 * Validator module is used by the code generated by {@link churi/compiler.js! compiler}.
 *
 * __Validator API considered unstable__ and may change for minor releases.
 *
 * @module churi/validator.js
 */
export * from './ucv-numeric-range.js';
