/**
 * Data serializer signature.
 *
 * Writes the given data `value` to the given `stream`.
 *
 * Serializers generated by {@link @hatsy/churi/compiler!UcsLib compiler}.
 *
 * @typeParam T - Serialized data type.
 * @param stream - Writable stream to serialize the data to.
 * @param value - Data value to serialize.
 *
 * @returns Promise resolved when data serialized.
 */
export type UcSerializer<in T> = (stream: WritableStream<Uint8Array>, value: T) => Promise<void>;
